language: php
sudo: false

php:
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - composer style-check
    - composer analyse
    - composer test-coverage

after_script:
    - |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
