language: php
sudo: false

php:
    - 7.3
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - composer style-check
    - composer analyse
    - composer test-coverage

after_script:
    - |
        if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
        fi
